#          YAML Reference Guide: https://docs.travis-ci.com/user/customizing-the-build/
# Environmental Variables Guide: https://docs.travis-ci.com/user/environment-variables/
#                YAML Validator: https://github.com/travis-ci/travis.rb#lint

# Notes:
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

branches:
  except:
  - gh-pages

language: generic

env:
  global:
  - secure: "XdVbG5aX7sm+oH21amR4oY3Vv9pI6PJZE1TWuLLLoXCl3o/yRqpDqNp91LKVZuEf727FK11vZ3r+kK0akg99iKLDFF3hEDpmddUpNvnR0Zpg3w9xd/PEiW0m78J83qtXMql4/SbS6okOcSrC3kYidaMgAEnjM3GXVnkyjQE0ODyE4HmLmgixEHiCI7zoiqtWqJhuIB2c0n104UjJfAwg42OY+AX2lo/bnptWLopmWCmyatlqVOw34XHHev02c2ZpXCHPU1vY0p9WdEmtHBrxITNPHwWL1NX40yflLamaUw/LbOTdMBVf5G+oVM5h0IdBijqt2k9msTvQCe2OO+4CohyrN1poXLgbsUK/60IBqNV9VJ4zF4gzbu2MofRh0RnSEUXhuM/zhYKYPOMFwBx1+X9hnChGRpILEg92Lc2cyLK6QB47WGoSb2M/L+VKSHDCVPGvCIiR26t5dcMBzQ20Hjo15zVWA+xECC0DiAZWl+15Nymjs45PX65gDY9sS6JjC7zlboRukdE2yZY/0TPBVKDtaaVVAi5tSL/6D7esNhzrLoft6+HdoUH4dPycG/Oiy9iT3yCHmRTCh3q+nzoSFGpBRtonBGkvZkeqe5xsrUoYJp2eX3oRVlCu1g2VwJppnw2wWHVTz/08ps389AEjNgZAsgHgp0v5qe/KByEpV3A="

matrix:
  include:
  - os: linux
    dist: bionic
    sudo: false
    addons:
      apt:
        sources:
        - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main"
          key_url: "https://packages.microsoft.com/keys/microsoft.asc"
        packages:
        - powershell
    language: python
    python:
    - "3.7"
    before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
    cache:
      directories:
      - $HOME/.local/share/powershell/Modules
      - $HOME/.nvm
      - $HOME/.npm
      - $HOME/virtualenv
  - os: osx
    osx_image: xcode11.2
    addons:
      homebrew:
        casks:
        - powershell
        update: true
    before_cache:
    - brew cleanup
    - rm -f $HOME/Library/Caches/pip/log/debug.log
    cache:
      directories:
      - $HOME/.local/share/powershell/Modules
      - $HOME/.nvm
      - $HOME/.npm
      - $HOME/Library/Caches/Homebrew
      - /usr/local/lib/python3.7/site-packages
  fast_finish: true

script:
- pwsh -File './build/build.ps1'

notifications:
  email: false
  webhooks:
    secure: TW5cUg3wHJLykGq3iBFv4zCUf0sWLsfSAzM4fuuhvN0dl2yLiHjrBoGge9qIb8pXsr8lMjFDsVqJJ69yw5ySyVmb1RWF3VTpY7SHSvzssY6taEfvr7l1WFCgpbg9sBm7F3FikkicXs8u1h329SS5uywzOeZyv2hpr/EqYfzdC2xY5muNzzX/l85zLH6jXjq5095WPFKPwuF7eSSrY4FZfEXW88Ivujjbmj0l9gw2YUlPPBZmxV1XYBk0jBuNqdW8YCWMpAglyTXBPzN+MDHz/FLro/pGzWFpH6KUneIFcheP7bm37dyeRkToLbUOmxIYSZskNZARuOMaBwHcVQkC/K+pMKl9k95uJrp1Rdhkic2u9DJUaEJghwjsrcHd36cKOF01UzMzXcxMgOmko3pwwlJNF0lBxZqm3NKDSg/tlUEW2iV+GbooboKEv68zJTvqS4vKUD8rxLHUTzrbAHmpTdOkk+WQbPK8JmyM0IXm5WypOAVYc94GQmEGNoPXtta5pWYDnE8J58qltx/MHjrS5P3n8bXJo2PNyYhsa7aZppFIqrDN7b/yJ1TuY2rOm24PONRZEBmPqlY/mgp4K2XNfu9dv3Dy7GkfL123uvTFZb580KmqvYvkOgJrWUZ5EM24cy5/NZWc3lGhPqrTcGMu54T+hAoQYOvh0GdKYki00Lg=
