#          YAML Reference Guide: https://www.appveyor.com/docs/appveyor-yml/
# Environmental Variables Guide: https://www.appveyor.com/docs/environment-variables/
#                YAML Validator: https://ci.appveyor.com/tools/validate-yaml

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

version: 1.0.{build}

branches:
  except:
  - gh-pages

skip_tags: true

pull_requests:
  do_not_increment_build_number: true

max_jobs: 3

image:
- Visual Studio 2017
- Previous Ubuntu

for:
- matrix:
    only:
    - PowerShell: 6
      image: Previous Ubuntu
  cache:
  - '$HOME/.local/share/powershell/Modules -> requirements.psd1'
  - '$HOME/.nvm'
  - '$HOME/.npm'
  - '$HOME/.cache/pip -> requirements.txt'
  - '$HOME/.local/lib/python2.7/site-packages -> requirements.txt'
  - '$HOME/.local/bin/mkdocs -> requirements.txt'
  build_script:
  - pwsh: ./build/build.ps1
- matrix:
    only:
    - PowerShell: 5
  cache:
  - '%USERPROFILE%\Documents\WindowsPowerShell\Modules -> requirements.psd1'
  - '%APPDATA%\npm'
  - '%APPDATA%\npm-cache'
  - '%LOCALAPPDATA%\pip\cache -> requirements.txt'
  - '%PYTHON%\Lib\site-packages -> requirements.txt'
  - '%PYTHON%\Scripts\mkdocs.exe -> requirements.txt'
  build_script:
  - ps: $env:PATH = "${env:PYTHON};${env:PYTHON}\Scripts;${env:PATH}"
  - ps: ./build/build.ps1 -DeploymentMode
# - matrix:
#     only:
#     - PowerShell: 6
#   cache:
#   - '%USERPROFILE%\Documents\PowerShell\Modules -> requirements.psd1'
#   - '%APPDATA%\npm'
#   - '%APPDATA%\npm-cache'
#   - '%LOCALAPPDATA%\pip\cache -> requirements.txt'
#   - '%PYTHON%\Lib\site-packages -> requirements.txt'
#   - '%PYTHON%\Scripts\mkdocs.exe -> requirements.txt'
#   build_script:
#   - pwsh: $env:PATH = "${env:PYTHON};${env:PYTHON}\Scripts;${env:PATH}"
#   - pwsh: ./build/build.ps1

matrix:
  exclude:
  - PowerShell: 5
    image: Previous Ubuntu
  - PowerShell: 6
    image: Visual Studio 2017

clone_depth: 50

environment:
  GITHUB_API_KEY:
    secure: C73uALUvX96LkyNxMJ2FtGMPHBANvjpviy9EFg33uYZowJEdS4DvsXS12fzT17BY
  NUGET_API_KEY:
    secure: u2jbw68/5JWUmA5z8fBok8TNO0BAJ41CSNGUJeVAtrIgDJ7p7TqW6dTbFmytP9UG
  COVERALLS_API_KEY:
    secure: hClQPXu5AWqBK5R49g0hrkhYtLgDpdftXlpMk2tTO1ba4FlsL6Q6BtpqR1QQPkRC
  matrix:
  - PowerShell: '5'
    PYTHON: C:\Python37-x64
  - PowerShell: '6'

test: off

deploy: off

artifacts:
- path: ./BuildOutput/TestResults.xml
  name: Pester Test Results
- path: ./BuildOutput/CodeCoverageResults.xml
  name: Pester Code Coverage Results

notifications:
- provider: Email
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false
- provider: GitHubPullRequest
  auth_token:
    secure: C73uALUvX96LkyNxMJ2FtGMPHBANvjpviy9EFg33uYZowJEdS4DvsXS12fzT17BY
    template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})"
- provider: Webhook # Gitter
  url:
    secure: VMG8UrlePL6sWol/IyQFbaCGkOLY9jFz+3wRnBG+rf95z9hLULTCpi+lN4xhSxwi4PyVEtDfstxeUA4/3+aP+g==
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
